---
# Production Inventory
# Update the IP address after provisioning your Lightsail instance

all:
  children:
    production:
      hosts:
        prod:
          ansible_host: localhost
          ansible_connection: local

      vars:
        env_name: production
        ansible_user: ubuntu
        ansible_python_interpreter: /usr/bin/python3
